apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: roboops-edge
resources:
  - namespace.yaml
  - service-account.yaml
  - deployment.yaml
images:
  - name: ghcr.io/example-org/roboops-ros2-edge-agent-cpp
    newTag: "0.1.0"
